### ISSUE TITLE
How to disable the spinner for CI?

### ISSUE THREAD

**Issue by binkley** [pitest/pitest-junit5-plugin#107]
I'd like to surface the "showSpinner" option in the Maven plugin so that I can disable it in my CI build environment (GitHub workflow).
The ASCII spinner fills my CI build log with lines like:

```
/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\
```

How can I do this?

**Comment by szpak** [comment]
Have you tried setting `verbosity` option to NO_SPINNER?

https://github.com/hcoles/pitest/blob/0df4d1a67e1002789420df64226c8c28c25408e1/pitest/src/main/java/org/pitest/util/Verbosity.java#L9-L10

**Comment by binkley** [comment]
Thanks @szpak, I didn't know about that.
Perhaps https://pitest.org/quickstart/maven/ could be updated to document the `<verbosity> ... </verbosity>` configuration option?
