### ISSUE TITLE
NoSuchMethodException with JUnit5 5.3.2 or higher

### ISSUE THREAD

**Issue by pkucia** [pitest/pitest-junit5-plugin#24]
When trying to run parametrized tests (with @ParametrizedTest) that use JUnit5 4.3.2 or higher
The following error is thrown when trying to run pitest on them:
```
10:59:31 AM PIT >> INFO : MINION : 1:59:31 AM PIT >> SEVERE : Description [testClass=com.test.SampleTest, name=testWithValidator(SegmentedQueryDefinition)]
java.lang.NoSuchMethodError: org.junit.platform.commons.util.ReflectionUtils.isMultidimensionalArray(Ljava/lang/Object;)Z
        at org.junit.jupiter.params.provider.MethodArgumentsProvider.toArguments(MethodArgumentsProvider.java:95)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[...]
```

It is caused by pitest-junit5-plugin that includes some classes from junit5 through shade plugin https://github.com/pitest/pitest-junit5-plugin/blob/master/pom.xml#L171 and causes mismatch above.

Why actually plugin need to include those classes rather than be explicitly set in dependencies?

It would be great if you can release new version of plugin that works with latest JUnit5.

**Comment by fakataha** [comment]
+1 Also affected by this issue

**Comment by MikeSafonov** [comment]
Hello
Any plans to fix this issue?

**Comment by anatoliy-balakirev** [comment]
I see this was fixed just by adding `org.junit.jupiter:junit-jupiter-params` to the shade plugin:
https://github.com/pitest/pitest-junit5-plugin/pull/36/commits/4a469f4f91bb6fb739b447b795ba4b7ddd5f47bc

But as @pkucia mentioned, why do we need to use that shade plugin in the first place? It seems to be quite fragile. If it's absolutely necessary, can we consider using:
`<include>org.junit.jupiter:junit-jupiter</include>`
instead of (which might be not everything we need there):
```
<include>org.junit.jupiter:junit-jupiter-engine</include>
<include>org.junit.jupiter:junit-jupiter-params </include>
```

**Comment by anatoliy-balakirev** [comment]
BTW, as a quick fix. This is an example of the failing code:
```
    @ParameterizedTest
    @MethodSource("getValues")
    void doSomething(final String value) {
        myFirstService.doSomething(value);

        verify(mySecondService).doSomethingElse(eq(value));
    }

    private static List<String> getValues() {
        return Arrays.asList("1", "2", "Some text");
    }
```
And when adjusted like this - it works fine (not getting to that check):
```
    @ParameterizedTest
    @MethodSource("getValues")
    void doSomething(final String value) {
        myFirstService.doSomething(value);

        verify(mySecondService).doSomethingElse(eq(value));
    }

    private static List<Arguments> getValues() {
        return Arrays.asList(Arguments.of("1"), Arguments.of("2"), Arguments.of("Some text"));
    }
```

**Comment by anatoliy-balakirev** [comment]
There is actually another issue, caused by this shade plugin. With version 0.9 (and 0.10-SNAPSHOT) I have following (using Gradle):
```
Caused by: java.lang.ClassNotFoundException: org.junit.jupiter.api.MethodOrdererContext
```
And then:
```
15:22:26 PIT >> FINE : According to coverage no tests hit the mutation MutationDetails
```
And finally:
```
>> Generated 154 mutations Killed 0 (0%)
>> Ran 0 tests (0 tests per mutation)
```
So no tests executed.

This is fixed when I replace:
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-shade-plugin</artifactId>
	<version>3.2.0</version>
	<executions>
		<execution>
			<goals>
				<goal>shade</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<artifactSet>
			<includes>
				<include>org.junit.platform:*</include>
				<include>org.junit.jupiter:junit-jupiter-engine</include>
			</includes>
		</artifactSet>
	</configuration>
</plugin>
```
With:
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-shade-plugin</artifactId>
	<version>3.2.0</version>
	<executions>
		<execution>
			<goals>
				<goal>shade</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<artifactSet>
			<includes>
				<include>org.junit.platform:*</include>
			</includes>
		</artifactSet>
	</configuration>
</plugin>
```
I.e. shading only what seems to be really required.

**Comment by Avinm** [comment]
This issue doesn't seem to be addressed with the PR linked. 
Is there an answer to the original question of `Why does the plugin need to include those classes rather than be explicitly declaring junit as a dependency`
In case there's a good enough reason to do so, could you relocate the shades to a shadow package to avoid class conflict?
https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html
