### ISSUE TITLE
pitest maven 1.9.0 seems to be incompatible with pitest junit plugin 0.16

### ISSUE THREAD

**Issue by stanKluk** [pitest/pitest-junit5-plugin#67]
Hello,

When trying to configure pitest-maven:1.9.0 with pitest-junit5-plugin:0.16, I have this error when running "mvn test-compile org.pitest:pitest-maven:mutationCoverage"

At the end of the process, I have this log : 
`17:58:01 PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
17:58:01 PIT >> INFO : Incremental analysis reduced number of mutations by 0
17:58:01 PIT >> INFO : Created  3 mutation test units in pre scan
17:58:01 PIT >> INFO : Sending 4 test classes to minion
17:58:01 PIT >> INFO : Sent tests to minion
17:58:01 PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
`

**When I downgrade pitest-maven to 1.8.1 ti works fine.**

Particularities of the project :
- openJdk 17.0.3
- multimodule (parent pom)
- junit 5
- Apache Maven 3.8.6  

To reproduce, you can chek these branches : 
https://github.com/stanKluk/airline-reservation/tree/working-pitest-1.81-with-plugin-0.16
https://github.com/stanKluk/airline-reservation/tree/not-working-pitest-1.9.0-with-plugin-0.16

Regards,
Stan

**Comment by hcoles** [comment]
@stanKluk As per the pitest release notes, the pitest junit 5 plugin must be updated to 1.0.0 when upgrading.

**Comment by stanKluk** [comment]
thanks for your response, at that time I didn't see the 1.0.0 on maven central
